[project]
name = "automatic-cuepoints"
version = "0.1.0"
description = "Automatically place cue points on tracks for easier mixing"
requires-python = ">=3.12"

dependencies = [
    "pyrekordbox",
    "ruptures",
    "librosa>=0.10.0",
    "tqdm",
    "matplotlib",
    "scipy",
    "numpy<2.0.0",
    "diskcache",
    "scikit-learn",
    "modal",
    "pyqt5; sys_platform == 'darwin'",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "ruff",
    "isort",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
package = false
python-preference = "only-system"
